### ISSUE TITLE
Asking about the not supply TLS certificate?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#249] opened 2019-11-13 03:30 UTC
Dear XRoad,
May I ask you about this error? I am runnig the XRoad version 6.22?
{
    "type": "Server.ClientProxy.SslAuthenticationFailed",
    "message": "Client (SUBSYSTEM:CAM/GOV/201902/TEST) specifies HTTPS but did not supply TLS certificate",
    "detail": "d093fd95-abc6-48d3-8213-7273d1352e16"
}
Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 03:38
Hi @darapenhchet 

Please see this X-Road Knowledge Base article for details:

https://confluence.niis.org/display/XRDKB/Client+Specifies+HTTPS+But+Did+Not+Supply+TLS+Certificate

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 04:01
Dear @petkivim ,
So for the Information System, it must use the Https too right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 06:34
Hi @darapenhchet 

It is recommended to use `HTTPS` in the traffic between the information system and Security Server. However, the Security Server administrator can manually change the setting to `HTTP`or `HTTPS_NOAUTH` as well.

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 06:44
Dear @petkivim 
Thanks your reply.
Could I ask you one more question?
Why the security server always show that error?

ee.ria.xroad.proxy.clientproxy.ClientException: Client.InvalidHttpMethod: Must use POST request method instead of GET

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 07:25
Hi @darapenhchet 

The error message is returned by the Security Server's SOAP interface in case it is invoked using `GET` request method. The SOAP interface supports `POST` request method only.

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 07:27
Dear @petkivim ,

But I don't use the SOAP interface. I use only the REST API.

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 07:34
Dear @darapenhchet 

The error message indicates that you're trying to invoke the SOAP interface. Please see below the URLs of the SOAP and REST interfaces.

**SOAP**
`https://<SECURITY_SERVER_HOST>`

**REST**
`https://<SECURITY_SERVER_HOST>/{protocol-version}/{serviceId}[/path][?query-parameters]`

The current REST protocol version is `r1`. In case the protocol version is not present in the URL as a first path parameter after the host, the request is processed by the SOAP interface. 

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 07:45
Dear @petkivim ,


Here is my request.
![image](https://user-images.githubusercontent.com/8038324/68743054-2d7d5800-0624-11ea-93f4-8a34aa8c9dd1.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 07:59
Hi @darapenhchet 

The request seems to be OK. Which version of the Security Server you're using? The REST interface is available starting from version `6.21.0`.

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 08:19
Dear @petkivim ,
Yes the Request is working well, but it still shows that error. I don't know how sovle that error message.

2019-11-13 15:16:35,489 [qtp1699265405-41] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (03a23da2-60a3-45d7-947c-ed6cebe27134)
ee.ria.xroad.proxy.clientproxy.ClientException: Client.InvalidHttpMethod: Must use POST request method instead of GET
	at ee.ria.xroad.proxy.clientproxy.ClientMessageHandler.verifyCanProcess(ClientMessageHandler.java:69)
	at ee.ria.xroad.proxy.clientproxy.ClientMessageHandler.createRequestProcessor(ClientMessageHandler.java:59)
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:89)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 08:31
Hi @darapenhchet 

Unfortunately, I'm not able to reproduce the error message. Could you send me the curl command that you're using the invoke the service?

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 09:18
Dear @petkivim ,

POST: https://206.189.145.147/r1/CAMBODIA/GOV/201901/TEST/INFO/

Header: "X-Road-Client" : "CAMBODIA/GOV/201902/TEST"

**Comment by petkivim** [comment] 2019-11-13 10:07
Hi @darapenhchet 

What's the result if you run the command below? Please replace `clientcert.pem` and `clientprivatekey.pem` with the names and location of your private key and certificate.

```
curl -E ./clientcert.pem --key ./clientprivatekey.pem -k -X POST -H 'X-Road-Client: CAMBODIA/GOV/201902/TEST' -i 'https://206.189.145.147/r1/CAMBODIA/GOV/201901/TEST/INFO/'
```

If you use `HTTPS_NOAUTH`, then the command is:

```
curl -k -X POST -H 'X-Road-Client: CAMBODIA/GOV/201902/TEST' -i 'https://206.189.145.147/r1/CAMBODIA/GOV/201901/TEST/INFO/'
```

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 10:23
Dear @petkivim ,

I have used the `HTTPS_NOAUTH` and it shows the result, but the XRoad Proxy is still show the error log. Is it the bug for XRoad 6.22?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-13 11:11
Hi @darapenhchet 

Unfortunately, I am not able to reproduce the error using the version 6.22.1. Therefore, it is not a bug.

I noticed that your Security Server is not protected by a firewall - it is accessible from the internet. Have you checked the IP address of the client which requests generate the error messages? I'm pretty sure that it is not your IP address and they are not your requests that generate the errors. Instead, it's probably a bot that is trying to access the Security Server's SOAP interface using a `GET` method which results in error messages in `proxy.log`. You can confirm this by checking the IP address of the client from `proxy.log`. For example:

```
2019-11-13 10:56:49,617 [qtp1005093407-48] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from X.X.X.X
2019-11-13 10:56:49,619 [qtp1005093407-48] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (08b5f21f-33fd-4075-8d96-65dad972f80c)
ee.ria.xroad.proxy.clientproxy.ClientException: Client.InvalidHttpMethod: Must use POST request method instead of GET
	at ee.ria.xroad.proxy.clientproxy.ClientMessageHandler.verifyCanProcess(ClientMessageHandler.java:69)
	at ee.ria.xroad.proxy.clientproxy.ClientMessageHandler.createRequestProcessor(ClientMessageHandler.java:59)
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:89)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
```

Regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-13 11:15
Dear @petkivim ,
Thanks for your help. Yes the Request IP adress looks like the bot. =

I will block the firewall.
Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment] 2019-11-14 02:54
Dear @petkivim ,

When I use the Https NO AUTH. It show errors like this.

curl -k -X POST -H 'X-Road-Client: CAMBODIA/GOV/201902/TEST' -i 'https://206.189.145.147/r1/CAMBODIA/GOV/201901/TEST/INFO/'

HTTP/1.1 500 Server Error
Date: Thu, 14 Nov 2019 02:54:22 GMT
Content-Type: application/json;charset=utf-8
X-Road-Error: Server.ServerProxy.IOError
Content-Length: 137

{"type":"Server.ServerProxy.IOError","message":"Received fatal alert: handshake_failure","detail":"b5b0c8d7-df83-4c93-a298-ff8d169a0ad3"}

**Comment by petkivim** [comment] 2019-11-14 04:22
Hi @darapenhchet 

This time the error is not related to the client side authentication method. The error message `Server.ServerProxy.IOError` tells that the problem is on the service provider side (`ServerProxy`). More details can be found on the provider side Security Server's `proxy.log`. 

One possible cause for the problem is that the "Verify TLS Certificate" checkbox is checked in the service configuration, but the TLS certificate of the service has not been uploaded on the Security Server. In that case the problem can be solved by unchecking the checkbox or uploading the certificate on the Security Server.

![image (3)](https://user-images.githubusercontent.com/575897/68826560-1b90c900-06a7-11ea-8206-e187117fc256.png)

Best regards,
Petteri

**Comment by darapenhchet** [comment] 2019-11-14 04:53
Dear @petkivim ,

I changed it to http it works now.
![image](https://user-images.githubusercontent.com/8038324/68827644-45f97b00-06d5-11ea-8acb-362bf3f65814.png)

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment] 2019-11-14 10:26
Dear @petkivim ,
May I know how to get this information in XRoad.

[](https://www.x-tee.ee/factsheets/EE/#eng)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment] 2019-11-14 10:48
Hi @darapenhchet 

That information can be collected using the Security Server `opmonitor` extension ([more information](https://github.com/nordic-institute/X-Road/blob/develop/doc/OperationalMonitoring/Architecture/arc-opmond_x-road_operational_monitoring_daemon_architecture_Y-1096-1.md)) and the Operational Monitoring Collector component ([more information](https://github.com/ria-ee/X-Road-opmonitor)).

Please note that the Operational Monitoring Collector component is maintained by the Estonian Information System Authority, not by NIIS.

Best regards,
Petteri

**Closed** 2019-11-18 03:03 UTC
