### ISSUE TITLE
Deletion of one service version in case of a multiple SOAP services, results in deletion of ACLs of all other versions of the same service

### ISSUE THREAD

**Issue by arattur** [nordic-institute/X-Road#1289] opened 2022-07-01 08:56 UTC
### Description
If there exists several versions of the same SOAP service (testService.v1, testService.v2, testService.v3...) and security server administrator deletes one of the versions (f.ex testService.v1) then access rights are also deleted from all other remaining versions.
### Steps to reproduce
Following steps are taken in Security Servers UI:
1. Add two versions of the same SOAP service in security server: ![1_serviceListView](https://user-images.githubusercontent.com/34676396/176856834-4ae0000f-8e8d-4917-9e8f-9e35fc13fe29.png)
2. Add access right to one of service versions and Save 
3. Check that access right is saved (**Note that ACL-s are assigned to service not service versions**, ie adding ACL to one version of a service "adds" the same ACL to all other versions of this service): ![2_serviceDetailedViewWithACL+Db](https://user-images.githubusercontent.com/34676396/176857106-2ac7cbe1-e14a-469f-8443-5f71c882a251.png)
4. Now delete one version of these services by clicking on service WSDL and then Delete
5. System deletes selected version of a service. All other service versions are not deleted as expected. **NB! With deletion of only one service version all access rights from other remaining versions are also deleted from database!** 
![3_afterDeletionListView+Db](https://user-images.githubusercontent.com/34676396/176858638-677265cd-e13b-4f60-a69b-22b3c145a811.png)
6. If you view access rights of a remaining service versions then they are displayed in UI (probably from some cache) but do not exist in database: 
![4_afterDeletionDetailedView+Db](https://user-images.githubusercontent.com/34676396/176858914-ce20c504-29a1-4859-9b2c-ab24df5903dc.png)

### Expected result
If there are more than one version of a service, then deletion of one version should not delete access rights of other remaining service versions.
### X-Road software version
Reproduced in Docker image: niis/xroad-security-server-standalone:bionic-7.0.2 but exists in other versions also

**Comment by vellotis** [comment] 2022-07-05 07:43
Hey, @autero1.
I already found the cause of the issue. The version of the service is not taken into account for the ACL if a service is deleted.

We will track it as a bug.

Ref: https://github.com/nordic-institute/X-Road/blob/76f35c73f011dbbf166916e2c44345bccd186872/src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/service/AccessRightService.java#L192-L195

**Comment by petkivim** [comment] 2022-08-19 10:51
Hi @arattur,

The fix to the bug has been implemented in this PR:

https://github.com/nordic-institute/X-Road/pull/1318

The fix will be included in X-Road version 7.2.0 that's released in Q4 / 2022.

Best regards,
Petteri

**Closed by petkivim** 2022-08-19 10:51 UTC
Labels: bug
